/// LOCALHOST
### Get Home 
GET http://localhost:3000/ 

### Get All 
GET http://localhost:3000/users

### Get One by Id 
GET http://localhost:3000/users/696992254effa511e0807fcc  
###
GET http://localhost:3000/users/696992404effa511e0807fcd 
###
GET http://localhost:3000/users/696992574effa511e0807fce

### Create a new one
POST http://localhost:3000/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Ernandez",
    "lastName": "Cortez",
    "email": "ernancortez.jss@gmail.com",
    "favoriteColor": "brown",
    "birthday": "17/03/1965"
}

### Modifiy One
PUT http://localhost:3000/users/696992254effa511e0807fcc HTTP/1.1
Content-Type: application/json

{
    "firstName": "Alfonso",
    "lastName": "Izelo",
    "email": "josealfonsoim.lds@gmail.com",
    "favoriteColor": "red",
    "birthday": "20/05/2008"
}

### Delet One
DELETE http://localhost:3000/users/696ab8ee629038cdc9bf2c2a

// PRODUCTION Deploy ### GET https://project-1-tdhp.onrender.com/ ### GET https://project-1-tdhp.onrender.com/users ### GET https://project-1-tdhp.onrender.com/users/69615eaefa7e5002b8398223 ### GET https://project-1-tdhp.onrender.com/users/69615f57fa7e5002b8398224 ### GET https://project-1-tdhp.onrender.com/users/69615f68fa7e5002b8398225  